### ISSUE TITLE
Extends Fails with "Page not found"

### ISSUE THREAD

**Issue by srsgores** [BKWLD/laravel-pug#1]
Any usage of the `extends` keyword, [as documented here](https://pugjs.org/language/extends.html), will result in the following error:

> Page not found.

It appears this may be due to [**not** specifying `basedir`](https://github.com/pug-php/pug/issues/63).

Usage ([as specified in the pug docs](https://pugjs.org/language/extends.html)):

_layout.pug_

```
doctype html
html
  head
    block title
      title Default title
  body
    block content
```

_index.pug_

```
extends layout.pug

block title
  title Article Title

block content
    h1 My Article
```

**Comment by weotch** [comment]
@srsgores Would you agree that `basedir` should be `resources/views`?

**Comment by srsgores** [comment]
@weotch. no.  I still get the same error when I set `basedir` to `"resources/views"`.  Can you replicate on your end?

**Comment by weotch** [comment]
@thelucre think you could take a look at this?

**Comment by thelucre** [comment]
@srsgores The `extends` syntax is a bit different than the official docs. See https://github.com/BKWLD/laravel-pug#extending-layouts 

I have an issue in with the php parser to get closer to the Jade proper syntax 
https://github.com/pug-php/pug/issues/69

**Comment by thelucre** [comment]
@srsgores Also note, the `basedir` should be absolute. The new config defaults with `'basedir' => resource_path('views')`

https://github.com/BKWLD/laravel-pug/blob/master/config/config.php#L9

**Comment by kylekatarnls** [comment]
Hi, extends layout.pug should works with index.pug and layout.pug in the same directory, else use relative path to your layout or absolute path starting with a slash and use the basedir option. This is the pugjs behaviour as far as I know.

**Comment by thelucre** [comment]
You're right. Thanks for the info!

**Comment by srsgores** [comment]
Guys, just tried using `/` in my path, but now I'm getting a different error:

> ErrorException in Parser.php line 70:
> The 'basedir' option need to be set to use absolute path like /layouts/main

Can anyone provide a sample of their `pug.php` config file?  Even when I set:

```
"basedir" => "/resources/views"
```

I still get this error.

**Comment by thelucre** [comment]
@srsgores You'll need to use the laravel function to pull the absolute path in your config. See my response above https://github.com/BKWLD/laravel-pug/issues/1#issuecomment-247127387

**Comment by srsgores** [comment]
@thelucre, I did notice that.  But even with the `resource_path("views")`, it still wouldn't work.  I don't think the library was accessing my `config/pug.php` file.  I had to manually edit `/vendor/bkwld/laravel-pug/config.php`, and add that line.  Not sure why yet.  Not sure how to manually update to [the latest commit](https://github.com/BKWLD/laravel-pug/commit/874deb5872134be6c7fad07b62cfa24701ff34d9#diff-215adb4f17e6c57786bec362c538ccb8R9), as [there's no version specified in `composer.json`](https://github.com/BKWLD/laravel-pug/blob/master/composer.json).

**Comment by kylekatarnls** [comment]
You can set the package version to "dev-master" (always prefer stable version), this setting allow you to get the last version of the master branch.

``` json
    "require": {
        "bkwld/laravel-pug": "dev-master"
    },
```
