### ISSUE TITLE
Error installation on laravel 11

### ISSUE THREAD

**Issue by ncsft** [BKWLD/laravel-pug#103]
composer require bkwld/laravel-pug:2.4.0
./composer.json has been updated
Running composer update bkwld/laravel-pug
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phug/phug[1.6.0, ..., 1.9.0] require symfony/var-dumper ^3.4 || ^4.0 || ^5.0 -> found symfony/var-dumper[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.36] but the package is fixed to v7.0.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phug/phug[1.10.0, ..., 1.12.3] require symfony/var-dumper ^3.4 || ^4.0 || ^5.0 || ^6.0 -> found symfony/var-dumper[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.36, v6.0.0, ..., v6.4.4] but the package is fixed to v7.0.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - bkwld/laravel-pug 2.4.0 requires phug/component ^1.1.3 -> satisfiable by phug/component[1.1.3, 1.1.4].
    - phug/component 1.1.4 requires phug/phug ^1.7.2 -> satisfiable by phug/phug[1.7.2, ..., 1.12.3].
    - phug/component 1.1.3 requires phug/phug ^1.6 -> satisfiable by phug/phug[1.6.0, ..., 1.12.3].
    - Root composer.json requires bkwld/laravel-pug 2.4.0 -> satisfiable by bkwld/laravel-pug[2.4.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by kylekatarnls** [comment]
Hello,

I didn't yet tested phug with Symfony 7, I'll give it a try before I release a tag

In the meantime you can use this branch:

```
composer require "phug/phug:dev-feature/symfony-7 as 1.13.0"
```

**Comment by kylekatarnls** [comment]
Phug 1.13.0 released fixes this issue.
