### ISSUE TITLE
Config does not work

### ISSUE THREAD

**Issue by fdorantesm** [BKWLD/laravel-pug#12]
Hi, today i've installed laravel-pug. I configured pug with these params but doest not work because is caching, has multiline and doesn't keep filename.

Following instructions i got:
    [InvalidArgumentException]  
    Configuration not found. 

Put following on app/config/packages/bkwld/laravel-pug/config.php not works. Config file is not included and config array's length is zero.

```
    'basedir' => resource_path('views')
    'cache'              => false,
    // 'stream'             => null,
    'extension'          => array('.jade'),
    'prettyprint'        => false,
    'phpSingleLine'      => true,
    'keepBaseName'       => true,
    // 'allowMixinOverride' => true,
    // 'allowMixedIndent'   => true,
    // 'keepNullAttributes' => false,
    // 'restrictedScope'    => false,
    // 'singleQuote'        => false,
    // 'filterAutoLoad'     => true,
    'indentSize'         => 2,
    'indentChar'         => ' ',
    // 'customKeywords'     => array(),
    // 'classAttribute'     => null,
```

Thanks, regards!

**Comment by kylekatarnls** [comment]
Hi, I will inspect this issue did you follow this section: https://github.com/BKWLD/laravel-pug#configuration

And are your on Laravel 4 or 5?

**Comment by fdorantesm** [comment]
Hi Kyle! Im using laravel 4 and i followed the instructions, even that's not right, it was necessary to add vendor path.

**Comment by kylekatarnls** [comment]
It closed the issue because of the description I gave to the pull request, but I'm not sure for this issue. I will try on Laravel 4. @WCLab can you tell me about what you had to do to solve your problem (to what have you add the vendor path ?)

**Comment by fdorantesm** [comment]
@kylekatarnls  I've added this param to the publish command: `--path=vendor/bkwld/laravel-pug/config`.

I'll watching for new releases, thanks.
