### ISSUE TITLE
Evaluating Class attribute doesn't work as expected 

### ISSUE THREAD

**Issue by bickle66** [BKWLD/laravel-pug#15]
Great work on this project but blade logic doesn't get evaluated on class attributes.

`li(class="{{ $show == 1 ? 'active' : '' }}")`

outputs to

`<li class="{{ $show == 1 ? 'active' : '' }}">`

**Comment by kylekatarnls** [comment]
We do not expect this to work, there is no brackets like that in pug.
`li(class=($show == 1 ? 'active' : ''))`
Should work.

**Comment by bickle66** [comment]
I had the above working on compiled pug -> blade through a gulp process. figured it should work here.

But that worked! Thanks,
