### ISSUE TITLE
cache is not cleared when i modify something I'm extending

### ISSUE THREAD

**Issue by acidjazz** [BKWLD/laravel-pug#17]
say `pages/home.pug` extends `layout/core.pug`

if i modify `home.pug` the cache is cleared and upon refresh i see the updated content, but this is not the case when i modify `layout/core.pug` , the cache will not reload until i again modify `pages/home.pug`

**Comment by kylekatarnls** [comment]
Indeed, this is a very tricky part since it means, the cache should detect all extends/includes in templates and recursively (extends/includes in extended/included files). It could make the cache system very heavy for just avoiding saving files manually. For production, you would have no problem if you follow this recommendation:
https://github.com/pug-php/pug#cache

**Comment by acidjazz** [comment]
@kylekatarnls thanks, any recommendations for development? is there any way to turn the cache off?

**Comment by kylekatarnls** [comment]
Of course, in dev, you can work with no cache at all:
```php
$pug->setOption('cache', false);
```

**Comment by acidjazz** [comment]
i tried that via dumping the config to `config/laravel-pug.php` which now is

```php
<?php return [
	// Required for extending layouts
	'basedir' => resource_path('views'),
	'cache'              => false,
];
```

and it's still caching and not updating, also ran `php artisan config:cache` and `php artisan cache:clear` to no luck

**Comment by kylekatarnls** [comment]
Maybe linked to this issue #12 I will inspect the config.

**Comment by kylekatarnls** [comment]
Hi, did you follow this section: https://github.com/BKWLD/laravel-pug#configuration

And are your on Laravel 4 or 5?

For now, I can confirm the bug on Laravel. I tested other config and followed instructions, but they are not taken into account.

**Comment by kylekatarnls** [comment]
Fixed, now you just have to wait @weotch merge the pull-request #18 and create a tag to update your projet.

**Comment by weotch** [comment]
@acidjazz Can you confirm that `dev-master` solves your issue before we tag it?

**Comment by acidjazz** [comment]
@weotch as soon as I get home I'll pull in dev-master and test!

**Comment by acidjazz** [comment]
@weotch @kylekatarnls just tested w/ dev-master, I can confirm this :bug: is fixed

**Comment by weotch** [comment]
@kylekatarnls You wanna release the tag with your new powers?

**Comment by kylekatarnls** [comment]
**1.3.0** released 😄
