### ISSUE TITLE
Assets management

### ISSUE THREAD

**Issue by kylekatarnls** [BKWLD/laravel-pug#19]
[pug-symfony](https://github.com/pug-php/pug-symfony) embed [pug-assets](https://github.com/pug-php/pug-assets) and [pug-minify](https://github.com/pug-php/pug-minify)

This stack allow any symfony user to have less, stylus, coffee and jsx files right in templates with no more install:

```pug
doctype 5
html
  head
    title Foo
    minify top
      script(src="foo/test.js")
      script(src="coffee/test.coffee")
      script(src="react-pug/test.jsxp" type="text/babel")
      link(rel="stylesheet" href="foo/test.css")
      link(rel="stylesheet" href="less/test.less")
      link(rel="stylesheet" href="stylus/test.styl")
      meta(name="foo" content="bar")
  body
    h1 Foobar
    minify bottom
      script(src="react/test.jsx" type="text/babel")
      script(src="coffee-pug/test.cofp")
      //- some comment
```

It also permit to concat and minify scripts and styles in production and provide a command to build all assets on deploy: `php bin/console assets:publish --env=prod`

I propose to implement the same feature in laravel-pug. What do you think about it?

**Comment by weotch** [comment]
Would you agree that all the work that this does is all pre-compilation of the view? So adding these features wouldn't increase overhead per-request?

**Comment by kylekatarnls** [comment]
1/ It's on autoload: only `link` and `script` inside the following tags (custom keyword): assets, concat, concat-to, minify, minify-to will be taken into account. If there are no such keywords in the templates anything is loaded.
2/ The publish command is here to build all the assets and the templates in the cache directory, then when users ask for, there is no pug compilation, no asset compilation, they get the PHP compiled template and the compiled (and/or concatanated and/or minified) JS and CSS assets. So this is a client optimization (if you minify) and server side if you follow the caching best practices (use the command and deploy and disable the cache check on production).

**Comment by weotch** [comment]
Cool, go for it.  Doesn't sound like a breaking change either; it's all additive.

**Comment by kylekatarnls** [comment]
Done: https://github.com/kylekatarnls/laravel-pug/compare/master...kylekatarnls:minify-assets

I added unit tests for this, so its based on the unit-tests branch and require first #27 to be merged.

**Comment by weotch** [comment]
#27 is merged now if you wanna send over that PR.
