### ISSUE TITLE
could u please add some sample

### ISSUE THREAD

**Issue by yozman** [BKWLD/laravel-pug#2]
could u please add some sample at `README.md`?

**Comment by nmsmith22389** [comment]
If it's pug example code you are looking for then just check out [here](https://pugjs.org/api/getting-started.html).

**Comment by fidgetwidget** [comment]
I think the kinds of examples that would be helpful here are how to use blade directives in the pug syntax.

from what I can tell, you'll want to use the :escaped filter and you'll need to handle both the beginning and ending statements for each directive. 

eg.
```
ul
  :escaped @foreach($array as $value)
  li {{ $value }}
  :escaped @endforeach
```


It would be nice if this had some custom keyword support for them
eg.
```
$pug->addKeyword('foreach', function ($args) {
    return array(
        'beginPhp' => '@foreach (' . $args . ')',
        'endPhp' => '@endforeach',
    );
});
```

**Comment by nmsmith22389** [comment]
Yeah I suppose I agree... It's not a very elegant solution because I feel like it messes some of the blade stuff up and doesn't work as well as I would like it to. The lack of docs isn't very helpful either.

ಠ_ಠ

**Comment by weotch** [comment]
I'm not a blade user myself.  If there is something you learned that wasn't immediately obvious, feel free to PR the README with it.

**Comment by partounian** [comment]
I noticed you closed this on grounds of the PR to README, but could the addKeyword functionality be added? Or does anyone know how to use the customKeywords passthrough for this? I have tried inputting the arguments of the above command in the passthrough array and with slight variations to no avail. Also noticed, I can't use a php function inside a tag/value (notable, the csrf_token function).

I have managed to escape the inline value by doing this, 
```input(type='hidden', value!="'. csrf_token() .'", name='_token')```
but the function doesn't get compiled into the value it comes out as plain text.

Note for others: Using the {{ csrf_field() }} works.

@weotch @fidgetwidget

**Comment by kylekatarnls** [comment]
`addKeyword` is not what you need here, then it neither the syntax to pass value, to call global functions just use:

`input(type='hidden' value!=csrf_token() name='_token')`

You can also use the raw code with:

`- csrf_field()`

If the functions are not global, you will have to pass it from your framework to view variables, see the helpers documentation: https://github.com/pug-php/pug#php-helpers-functions

**Comment by Konafets** [comment]
Just want to add some of my experience with PUG and Blade: 
It does not work or on a very inconvenience level. The code looks really bad and the mixture of Blade and PUG does not always work. Mainly because of the expected indention of PUG.

However, I found another nice way to use PUG with Laravel: VueJs and VueLoader. It is described here: https://vuejs.org/v2/guide/single-file-components.html

I just leave it here as an alternative.

**Comment by kylekatarnls** [comment]
Vue.js is a really different approach. For example, to inject data in template since, you send data and template and let the client compile it. With pug server-side, you send to the client rendered HTML with data already compiled in it.

But what I really not undrestand is what mix blade an pug? It seems redundant to me (`each`, mixins, expression insertion), all exist in pug.

**Comment by Konafets** [comment]
Yes, the approach is different. Regarding the mix of blade and pug: I thought you are bound to use Blade for things like iterations and did not looked carefully to the pug documentation. Thanks for pointing it out.

**Comment by kylekatarnls** [comment]
Blade iterations are very verbose. And Pug iterations indent is meaningful. I recommend:

```pug
each item in items
  p=item
```

over any blade wrapping for iterations.

Also prefer to well learn and use 1 template engine rather than use several and miss nice features.

**Comment by partounian** [comment]
Just starting off I am using pug to simply have the HTML look clean while using blade for the logic.

**Comment by partounian** [comment]
Also the reason I was asking about custom keywords is so I can use the blade logic without :escaped

**Comment by kylekatarnls** [comment]
What do you call blade logic? Sections is block in pug, component is mixin, can you tell me what feature of blade you would implement as a new keyword? Because both blade and pug are very complete template engines and I don't see what would miss. Are you looking for the `$loop` information feature?

**Comment by partounian** [comment]
Foreach for example.

**Comment by kylekatarnls** [comment]
As I already say here: https://github.com/BKWLD/laravel-pug/issues/2#issuecomment-289381418 and here: https://github.com/BKWLD/laravel-pug/issues/2#issuecomment-289289313 foreach exists in pug:
`each item in items` is exactly the same as `@foreach ($items as $item)`, do not reinvent the wheel, take benefit of existing features.

We should not implement blade helpers until having a good reason to do it.

**Comment by partounian** [comment]
My apologies, I thought the foreach in pug would only be using JS variables, I did not realize it is integrated that nicely with Laravel's PHP.

**Comment by kylekatarnls** [comment]
Glad it works for you now. :)

**Comment by Konafets** [comment]
What is the equivalent of @yield and @stack in pug?

**Comment by kylekatarnls** [comment]
See block and append. Should acheive the same goal.

**Comment by Konafets** [comment]
Thanks, one more question:

I have this code 
```
html(lang="{{ config('app.locale') }}")
```

According to this [comment](https://github.com/BKWLD/laravel-pug/issues/2#issuecomment-289255283) the usual moustache syntax should work, but it does not. I got 

```
<html lang="{{ config('app.locale') }}">
``` 
 in the FE.

I also tried `- config('app.locale')`, which does not work out neither.

**Comment by fdorantesm** [comment]
You don't need to use moustaches.

`html(lang=config('locale'))

**Comment by smsonn** [comment]
how to get data from database in view page. then make fetch for this data ?
example
var get_data = DB::table('tableName')->get()
@foreach($get_data as $a)
    {{ $a->id }}
@endforeach
