### ISSUE TITLE
Cli settings

### ISSUE THREAD

**Issue by kylekatarnls** [BKWLD/laravel-pug#22]
Hi,

Just a note to speak about what I did in pug-symfony recently and could be done in laravel-pug:
https://github.com/pug-php/pug-symfony/commit/da85a33a5e36540e6a4461752a09441d91325a3f

It's a script triggered after `composer require thepackage`, it ask some questions to the user and change settings accordingly to his answers.

The same system could allow the config step (https://github.com/BKWLD/laravel-pug#configuration) to be done automatically.

**Comment by weotch** [comment]
Wow, cool!  I just read about this: https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518.  I think this feature of 5.5 will take care of that specific configuration step very soon.  You agree?

**Comment by kylekatarnls** [comment]
@gabriel-caruso took this action. I tested his pull-request, it perfectly works.

With:
```json
...
"require": {
  "bkwld/laravel-pug": "dev-master",
  "laravel/framework": "dev-master",
```
And install step 2 (add the service provider) is no longer needed to get pug templates rendererd.

**Comment by weotch** [comment]
I'm for tagging a new minor release  and closing this issue.  Cool?

**Comment by kylekatarnls** [comment]
I think it's a good start, but we can also skip the step 2 on laravel < 5.5 using the same way as in https://github.com/pug-php/pug-symfony, that's why I started this branch: https://github.com/BKWLD/laravel-pug/tree/auto-publish-vendor

Let resume, install/config steps are:
1. composer require bkwld/laravel-pug
2. Add the service provider to your app.php providers: Bkwld\LaravelPug\ServiceProvider::class
3. Execute config:publish (laravel 4) vendor:publish (laravel 5)

It's nearly the same as in symfony, so we should be able to do steps 2 and 3 automatically on composer require/update/install. The auto-discovery only do 2 for laravel 5.5+.

**Comment by kylekatarnls** [comment]
But patch/minor version can be released for that yet.
