### ISSUE TITLE
View::compose() doesn't pass data to pug partials

### ISSUE THREAD

**Issue by elizabethclouser** [BKWLD/laravel-pug#23]
Laravel version: 5.4

## app/Http/Composers/CurrentUserComposer

```
<?php namespace App\Http\Composers;
 
use Illuminate\Http\Request;
use Auth;
use App\User;
use Illuminate\View\View;
 
class CurrentUserComposer
 {
     public function compose(View $view)
     {
          $view->with('user', Auth::user());
     }
 }
```

## app/Providers/ComposerServiceProvider.php

`View::composer('admin.dashboard', 'App\Http\Composers\CurrentUserComposer');`
 ^ Passes $user to the admin.dashboard.pug template

`View::composer('admin.partials.header', 'App\Http\Composers\CurrentUserComposer');`
^ But this doesn't send $user to the admin.partials.header.pug partial 

The partial is rendering when called with `include` in the master layout, but the data isn't being passed.

**Comment by weotch** [comment]
Instead of using `include`, what if you do something like:

```pug
.whatever!= view('admin.partials.header')
```

In other words, use Laravel's view renderer rather than Pug's `include`.  I'm guessing it doesn't work as you've described because Laravel isn't managing the rendering of the partial and thus the `composer` hook can't do it's thing.

**Comment by kylekatarnls** [comment]
Hi @jamesclouser, glad you can make it work. I would be interested in seeing if there is something we should improve. The `Pug` class has a `share` method that allows to share a variable for all views rendered with Pug. Ideally, laravel-pug should be intuitive and works like blade.

Can you confirm the following?

You have the following `admin.dashboard.pug`:
```pug
include admin.partials.header
if user
  footer user exists
```
And `admin.partials.header.pug`:
```pug
unless user
  header user does not exist
```
And you use with to set the user.
```php
$view->with('user', Auth::user());
```
And get:
```html
<header>user does not exist</header>
<footer>user exists</footer>
```

Right?
