### ISSUE TITLE
Unit tests and continuous integration

### ISSUE THREAD

**Issue by kylekatarnls** [BKWLD/laravel-pug#26]
Hi,

I started to code unit tests to ensure all still working as expected in all PHP and Laravel versions:

https://github.com/kylekatarnls/laravel-pug/pull/1

I have not enough rights to enable TravisCI (https://travis-ci.org) to execute unit tests on different PHP/dependencies versions.

I would also recommand to enable the tools we use on our projects:
- https://styleci.io for code style
- https://codeclimate.com for code complexity and anti-patterns and test coverage
- https://codecov.io (or codeclimate with coverage pull-request enabled) for test coverage

All those CI tools will check every commits and every pull-request to ensure they can be merged safely.

**Comment by weotch** [comment]
I setup accounts on:

- travis
- styleci
- codeclimate
  - Here is the reporter id if you want to set it up code coverage there `b9dac85e7024fb18994b92d2d92f8026cd9be15ef620b9a9f4095e6754a1b3de`

**Comment by weotch** [comment]
Nvm, I went ahead with https://codecov.io

Thanks for doing all of that work!  Awesome!
