### ISSUE TITLE
Refreshing in browserSync in elixir?

### ISSUE THREAD

**Issue by nmsmith22389** [BKWLD/laravel-pug#3]
Could you tell me how to add it to also cause a refresh in elixir? Everything will trigger a refresh on change except the pug files.

**Comment by weotch** [comment]
I'm not an elixir user, but maybe you could setup browserSync to watch the `storage/framework/views` directory ... that's where compiled templates end up.

**Comment by nmsmith22389** [comment]
Yeah I tried that but it seems to override the other watch folders and breaks the others. Elixir is supposed to make everything easier but it has almost no configurability. I'm starting to think it was a mistake to use it instead of just plain gulp. I'm not very familiar with Elixir and I can't really find much documentation.

**Comment by nmsmith22389** [comment]
Do you think it would be better to switch to an elixir based converter? I think that would fix the problem maybe.

**Comment by Riant** [comment]
My gulpfile.js content, wish it is useful for you.
```
const gulp = require('gulp'),
    shell = require('gulp-shell');
var pug_changed_type = 'single';

var browserSync = require('browser-sync').create();

gulp.task('watch', function(){
  var pug_watch = gulp.watch(['resources/views/**/*.pug'], ['clear-cache-then-reload']);
  
  pug_watch.on('change', function(event){
    var paths = event.path.split('\\');
    pug_changed_type = (paths[paths.length-2] === 'part' || paths[paths.length-1].indexOf('_') === 0) ? 'part' : 'single'; // The file which in the part folder or whose name start with _
  });
});

gulp.task('clear-cache-then-reload', function(done){
  if(pug_changed_type === 'part'){
    console.log('Clear View Cache');
    gulp.src(['storage/framework/views/*.php']).pipe(shell('php artisan view:clear'));
    setTimeout(function(){
      browserSync.reload();
      done();
    }, 500);
  } else {
    browserSync.reload();
    done();
  }
});
```
