### ISSUE TITLE
Custom directives just echo out to page

### ISSUE THREAD

**Issue by bickle66** [BKWLD/laravel-pug#31]
I am using [critical-css](https://github.com/kalfheim/critical-css) which has a custom directive

`@criticalCss('some/route')`

This works in blade fine, so I can work around this by ```@including('critical')``` but has anybody else experienced this problem with custom directives on Laravel 5.4 & laravel-pug 1.3.1?

**Comment by kylekatarnls** [comment]
With the extension `.pug.blade`, you should be able to mix blade and pug like this:

```pug
p Pug code

@criticalCss('some/route')

p Pug code
```

Do you get trouble with this code?

**Comment by bickle66** [comment]
Yeah, that's what I have and it just writes it out on the screen.

I just did a little test and wrote my own custom directive:

```
Blade::directive('test', function($expression) {
    return "<?php echo 'Hello ' . {$expression}; ?>";
});
```

```@test('Bickle66')```

from a `pug.blade` just outputs `@test('Bickle66')`

but from a regular blade outputs

```Hello Bickle66```

So I can confirm custom directives are not working in pug.blade (at least for me).

**Comment by kylekatarnls** [comment]
Hi,

Sorry, I forgot the API. In fact, the .pug.blade is not a real mixed syntax (it would be too messy), it's a first step of pug compilation, then blade compilation, it means, the whole template code must have a valid pug syntax. And this pug template must render a valid blade template, so you can do this:

```div.
    @if (1 === 1)
        1 = 1
    @endif
```
Note there is a dot after `div`, that means for pug everything inside the div is just text, so this will become:

```<div>
    @if (1 === 1)
        1 = 1
    @endif
</div>
```

Then blade will take that code and render:

```<div>
    1 = 1
</div>
```

The same will be possible for your custom directive, for example, you should be able to do:

```
p Pug code

| @criticalCss('some/route')

p Pug code
```

Can you confirm this syntax, so I will explain all that in the README.

**Comment by bickle66** [comment]
I can confirm that with, or without the pipe | it is still producing the same results.

I know the directive works because I can see it from a regular blade, but this:

```
| @extends('layouts.app')
| @section('content')
| @test()
.jumbotron
  .container
    .row
      .col-md-8.col-md-offset-2
        h1 Some Headline
.container
  .row.padding-top
    .col-md-8.col-md-offset-2.text-center
      p.lead By modernizing the way your company does business...
| @endsection
```

produces the entire rendered content section within my layout, but with:
`@test()`
above the jumbotron. _without_ the pipe.

If I remove the pipe, I get identical results.

**Comment by kylekatarnls** [comment]
Sorry. OK, I understand. As the `.pug.blade` has its own blade engine inside, it does not get the customizations. I will try to fix it.

Beside, you can set a pug directive:

```php
<?php

use Alfheim\CriticalCss\BladeUtils;

app('laravel-pug.pug')->addKeyword('criticalCss', function ($expr) {
    return BladeUtils::parseBladeDirective($expr);
});
```

So you can use it directly in the pug code:

```pug
p Pug code

criticalCss some/route

p Pug code
```

**Comment by kylekatarnls** [comment]
Custom directives are now available in `.pug.blade` templates.

Please tell me if all is fine for you or if you get any trouble.

**Comment by kylekatarnls** [comment]
We released a fix to get custom blade directive. You can just update to the last version (1.4.1) with `composer update`

**Comment by bickle66** [comment]
Worked like a charm! Thanks!
