### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by montyclt** [BKWLD/laravel-pug#34]
My project broken after `composer update`

Pug 3 has breaking changes.

In my case, in last pug version I was using PHP syntax in all except each loop, and in Pug 3 in need use PHP syntax in all.

Example in old pug:
```
each item in items
    tr
        td= $item->name
```

In pug 3, I need do:
```
each $item in $items
    tr
        td= $item->name
```

This is my breaking change, but are more in [Pug 3](https://github.com/pug-php/pug/blob/master/CHANGELOG.md).

I propose you change this package version thats use Pug 3 to 2.*.*, that allow any person do `composer update` and doesn't break theirs projects.

**Comment by kylekatarnls** [comment]
bkwld/laravel-pug is compatible with both pug-php 2 and 3, so you can downgrade pug-php with no conflict with laravel-pug as you can see in our unit tests (https://travis-ci.org/BKWLD/laravel-pug):

`composer require pug-php/pug:^2.7`

But I should warn you: pug-php 2 can become deprecated.

As you can see the old syntax was inconsistent for PHP-style syntax:
```pug
each item in items
    li= $item->name
```

The new version brings more customization, consistency, pugjs compliancy and use a more structured engine that will be used by several pug ports. This engine is about to become the standard and will be soon full-documented. So I encourage you to upgrade and adapt your code.

Neverless, I will consider replacing 1.5 version with 2.0.

**Comment by montyclt** [comment]
Yes, I agree the old syntax is inconsistent with PHP syntax, I used search and replace in my project to fix it and I'm using Pug 3 (I'm really appreciate you work of new engine ❤️ ), but the problem is someone that only require `"bkwld/laravel-pug": "^1.3"` in his `composer.json` file like me and then run `composer update` breaks his project.

**Comment by kylekatarnls** [comment]
I thought a lot of it and realized that removing the tag would be even worst. But it could be possible to detect is someone is requiring `laravel-pug` in a way that allows both <1.5 and >=1.5 to warn him and give him a link to the documentation.
