### ISSUE TITLE
Route::is('home')  

### ISSUE THREAD

**Issue by GMounir** [BKWLD/laravel-pug#35]
Hello, after i do composer update All the pug templates are broken even the variables with **$value** i have to remove the $ to pass, but for **Route::is('home')** not working i spend all the day trying fix the problem with no result.
some help please...

**Comment by kylekatarnls** [comment]
Hello, if all your expressions are in PHP (variables with $), you should set the option: `'languageExpression' => 'php'`
Route::is should not be a problem even in JS style, I will check why it could fail.

**Comment by GMounir** [comment]
Thank you @kylekatarnls for reply , i returned back to **pug-php/pug "^2.7"** version, i will try your solution today

**Comment by kylekatarnls** [comment]
Hi,
I get `Route::is('home')` working with both modes. I close this. If you still have trouble please provide more code and context to help me to reproduce your bug.

Thanks,
