### ISSUE TITLE
@php directive doesn't work

### ISSUE THREAD

**Issue by bickle66** [BKWLD/laravel-pug#38]
I have a loop that I set a variable so I use the @php & @endphp directives.

This worked in 1.4.1 and below, but broke in ^1.5.0

I get a weird doubling up of php tags in the compiled view.

```
<?php<?php 
\Phug\Renderer\Profiler\ProfilerModule::recordProfilerDisplayEvent(17);
// PUG_DEBUG:17
 ?>
```

**Comment by kylekatarnls** [comment]
I will inspect. Meanwhile, you can use the pug PHP filter.
```pug
:php
  $var = my_function();
```

**Comment by kylekatarnls** [comment]
After inspection, the problem come from the change we made for indented contents. It concerns only 2 blade directives: `@php` and `@verbatim`. It would be risky to implement a custom handle of them. And you can use both like this:

```pug
div
    | Any pug code here
    //- then you can put a dot and indent blade code:
    .
        @php
        $hours *= 2
        @endphp
    p=hours
    //- or a dot after any of tag/class/id/attributes
    div#foo.bar(a="a").
        @verbatim
        @if here will not be parsed
        @endverbatim
```

And the better solution for PHP embedded still remains the pug PHP filter if it does not generate blade code that you would keep not parsed.

I hope the solution of a global search/replace of your @php directive could be fine for you.
