### ISSUE TITLE
Indent of blade code

### ISSUE THREAD

**Issue by Konafets** [BKWLD/laravel-pug#4]
Consider I have this blade code in my template:

```html
...

@if (Route::has('login'))
    <div class="top-right links">
        @if (Auth::check())
            <a href="{{ url('/home') }}">Home</a>
        @else
            <a href="{{ url('/login') }}">Login</a>
            <a href="{{ url('/register') }}">Register</a>
        @endif
    </div>
@endif

...
```

which looks like this in pug:

```pug
...

@if (Route::has('login'))
div.top-right.links
@if (Auth::check())
a(href="{{ url('/home') }}") Home
@else
a(href="{{ url('/login') }}") Login
a(href="{{ url('/register') }}") Register
@endif
@endif

...
```

For the sake of better structure I like to indent the blade keywords here too, so that I have the snippet which looks like:

```pug
@if (Route::has('login'))
    div.top-right.links
    @if (Auth::check())
        a(href="{{ url('/home') }}") Home
    @else
        a(href="{{ url('/login') }}") Login
        a(href="{{ url('/register') }}") Register
    @endif
@endif
```

However, I get a `ErrorException in Parser.php line 248:
(24) : Unexpected token "indent"` error

Is there a workaround or hidden feature in pug?

**Comment by weotch** [comment]
I don't think so, Pug is very specific about how you use indenting.  But I'm not expert-grade in pug/jade.  If it's possible, I imagine it's in the Pug docs: https://pugjs.org/api/getting-started.html
