### ISSUE TITLE
How to call static methods in Pug 3?

### ISSUE THREAD

**Issue by weotch** [BKWLD/laravel-pug#42]
@kylekatarnls is it no longer possible in version 3 of https://github.com/pug-php/pug to call static methods from pug?  Like Laravel facade methods?

For instance:

```pug
html
  head
    title= Layout::title()
```

This currently errors with:

```
Parse error: syntax error, unexpected ';', expecting ',' or ')'
```

The compiled PHP looks like:

```php
<title><?= htmlspecialchars((is_bool($_pug_temp = (isset($Layout) ? $Layout : null);
(function_exists('title') ? title() : call_user_func((isset($title) ? $title : null)))) ? var_export($_pug_temp, true) : $_pug_temp)) ?></title>
```

Do I have to use the `share()` helper function?  https://github.com/pug-php/pug#php-helpers-functions

**Comment by kylekatarnls** [comment]
Hum, strange, I test the following: `p=DateTime::createFromFormat('j-M-Y', '15-Feb-2009')->format('j')` in both PHP and JS expressionLanguage and it's still working on pug-php 2 and 3.

A more strict exception test might be needed in the js-phpize extension.

**Comment by kylekatarnls** [comment]
Hi, I introduce new unexpected tokens in `js-phpize` that are not valid in JS like `::` to throw lexer exceptions and so force `pug-php` to fallback to the PHP language.

Can you try to update your dependencies?

**Comment by weotch** [comment]
Yup, that fixed it!  Thanks!
