### ISSUE TITLE
Add https://www.phug-lang.com to your GitHub Description

### ISSUE THREAD

**Issue by ghost** [BKWLD/laravel-pug#46]
Because it took a while for me to discover, that your package is based on "phug", I would recommend you to add [https://www.phug-lang.com](https://www.phug-lang.com) as a language reference to your GitHub description page.

Thx!

**Comment by kylekatarnls** [comment]
Hi, in fact laravel-pug used pug-php before pug-php use Phug. Phug is the merge of pug-php and tale-pug into a common project with more customization and more documented. We will put a link. If you think of a particular place in the README you can send us a pull-request.

**Comment by kylekatarnls** [comment]
Done.
