### ISSUE TITLE
How to be sure that the ExceptionHandler is working?

### ISSUE THREAD

**Issue by ghost** [BKWLD/laravel-pug#47]
I’ve created a class with the code of your GitHub page and put it into `app/Exceptions/ExceptionHandler.php`. Is that correct?

How can I be sure that it works?

**Comment by kylekatarnls** [comment]
To test the exception handler, throw an exception :)

Runtime error:
```pug
p=1/0
```

Custom exception:
```pug
:php
  throw new \Exception('custom');
```

The exception handler should show you the tag/filter the error come from.
