### ISSUE TITLE
 how to minify

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#49]
Thanks for this works very well, you can modify the file.pug

**Comment by kylekatarnls** [comment]
Sorry, I did not understand which modification and which file.pug you're talking about.

About minifcation, you can check the pug-minify documentation (the module we used internally):
https://github.com/pug-php/pug-minify

**Comment by GeometryRamiroGarcia** [comment]
I mean all the pug files of the project, I'm new to laravel. Minifying pug files is best done when the project is published ?

**Comment by kylekatarnls** [comment]
First you need to wrap your assets in `minify` blocks (as shown in the README of https://github.com/pug-php/pug-minify).

Then Laravel has an environment system. For example when you run `php artisan serve`, the environment is "development" by default (if so pug-minify will not minify your assets to help you to debug).

And when running your site with Apache or nginx, the environment is "production" by default. There pug-minify concat and minify your assets.

See also Laravel env settings: https://laravel.com/docs/5.6/configuration

**Comment by GeometryRamiroGarcia** [comment]
Thanks @kylekatarnls
