### ISSUE TITLE
Compiling blade code in pug templates

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#50]
@kylekatarnls :)

It works and compiles perfectly

![screen shot 2018-04-24 at 11 20 31 am](https://user-images.githubusercontent.com/38221701/39200350-8c988496-47b1-11e8-9ebb-5fa888d464be.png)

![screen shot 2018-04-24 at 11 21 02 am](https://user-images.githubusercontent.com/38221701/39200365-99351020-47b1-11e8-86fb-459ad0d322a0.png)

### *************************************

But if I use an `extend` or `if`, it does not compile.

![screen shot 2018-04-24 at 11 28 24 am](https://user-images.githubusercontent.com/38221701/39200765-a6c3c1f4-47b2-11e8-88e6-14ff8cfc997b.png)

![screen shot 2018-04-24 at 11 28 06 am](https://user-images.githubusercontent.com/38221701/39200769-a9d48770-47b2-11e8-9a9f-cb268f13e2d3.png)

_Thanks for the help you can give me_

**Comment by kylekatarnls** [comment]
I recommend to use pure pug template (extends, :php filter and if/elseif all exist in pug) rather than mixing blade and pug code. But if you still want to use both, you need to name the file with .pug.blade extension as mentioned in the README.

**Comment by GeometryRamiroGarcia** [comment]
Thanks @kylekatarnls
