### ISSUE TITLE
Options blade in pure pug

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#51]
Sorry for this beginner question I'm a novice @kylekatarnls.

I'm using only pug as you advised me. But I do not know how you can use this type of options that we offer balde

`link(rel='stylesheet', href='{{ URL::asset('css/main.css') }}')`
`html(lang="{{ app()->getLocale() }}")`

**Comment by kylekatarnls** [comment]
Default setting allow you to use JS-style syntax (like in the original pugjs).
```
link(rel='stylesheet' href=asset('css/main.css'))
html(lang=app().getLocale())
```

Else you can set the expressionLanguage to php to use PHP expressions (faster execution).

**Comment by GeometryRamiroGarcia** [comment]
Thank you where I can change expressionLanguage

**Comment by Illiou** [comment]
@kylekatarnls When I try to use this line `html(lang=app().getLocale())` I only get the following PHP error:
`Function name must be a string`

Just a single view, this single line, no settings changed.

**Comment by kylekatarnls** [comment]
What is your Laravel version?

**Comment by Illiou** [comment]
Ah sorry, Laravel 5.7.2, Windows 10.

**Comment by kylekatarnls** [comment]
Sorry, it's a bug from our engine, you can use `html(lang=app()->getLocale())` until we fix it.
