### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#52]
Where I can change expressionLanguage

**PUG**
```
- var values = [];
ul
  each val in values
    li= val
```

**BLADE**
```
@foreach ($views as $view)
           {{ $view->name }}
@endforeach
```

 **BKWLD/laravel-pug**
 I do not know if it's like that?
```
- var values = {{$views}};
ul
  each val in values
    li= val
```

**Comment by kylekatarnls** [comment]
`'expressionLanguage' => 'php'` can be set in config/laravel-pug.php (see https://github.com/BKWLD/laravel-pug#configuration)

But it seems you use JS-style (the default value), so just use your input variable and just forget blade `@` and `{{ }}`, Pug does not use it:
```pug
ul
  each val in views
    li= val
```

**Comment by GeometryRamiroGarcia** [comment]
Thanks @kylekatarnls
