### ISSUE TITLE
Bemto mixins does not work

### ISSUE THREAD

**Issue by explicit-logic** [BKWLD/laravel-pug#53]
Hi there. 
Bemto mixins (https://github.com/kizu/bemto) for writing BEM-style code for Pug does not work.

https://i.imgur.com/gCUVjKs.png

### Steps to reproduce bug
1. Clone bemto repository to views:
```
 cd project-dir/resources/views
 git clone git://github.com/kizu/bemto.git
```
2.  Add route 
   ```
Route::get('/bemto',function(){
      return view('bemto.test.cases.1_basics');
});
   ```
3.  Go to *http://site-name/bemto* .

**Comment by kylekatarnls** [comment]
Hi,

**laravel-pug** use a PHP engine to render the pug code. It can handle simple JS code by converting it into PHP but it does not run JS code, else it would disallow to use PHP objects in your pug templates.

As you can see bemto is deeply tied to JS stuffs: https://github.com/kizu/bemto/blob/master/lib/bemto.pug

A simple example: `options && options.tag || ( typeof options == 'string' ? options : '')` this can returns any data type in JS, but it can only returns a boolean in PHP.

If you're sure you need JS and don't care anymore about running PHP stuffs in your pug templates, you can use the option `'pugjs' => true,` (add it in **/config/laravel-pug.php**). It will use the native npm pug package instead.

**Comment by kylekatarnls** [comment]
Note: mixins won't just work by cloning the repository. You must include the **bemto/bemto.pug** file (using the right path according to where you put it) as mentioned on the project README.

**Comment by explicit-logic** [comment]
I set option `'pugjs' => true`, and installed `npm i pug`, but this did not solve the problem. https://i.imgur.com/udi2yT5.png

**Comment by kylekatarnls** [comment]
Sorry, it's not `npm i pug`, this will search in your local node_modules. Remove your vendor directory, then re-install with `composer install`. When you're asked to install the pug node package, enter `Y` and enter to install it.

I guess, you answered *no* and remember the choice the first time so as the pugjs package cannot be found in its expected place, it fallback on the PHP engine.

**Comment by explicit-logic** [comment]
Still does not work :disappointed:  

How to check that this package is installed?
My OS is Windows 10, I use homestead.

**Comment by kylekatarnls** [comment]
The pug node package is installed in **vendor/nodejs-php-fallback/nodejs-php-fallback/node_modules/pug-cli** so in your case, you must find it in **/home/vagrant/code/molfar/vendor/nodejs-php-fallback/nodejs-php-fallback/node_modules/pug-cli** and the config `'pugjs' => true` to enable it should be in **/home/vagrant/code/molfar/config/laravel-pug.php**

**Comment by kylekatarnls** [comment]
I close this and assume you get it working with pugjs native engine. But feel free to ask if you need further help for this.
