### ISSUE TITLE
Laravel Javascript

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#54]
how can I use this function of this [plugin](https://github.com/cretueusebiu/laravel-javascript)
{{ ScriptVariables::render() }}

**Comment by kylekatarnls** [comment]
As any expression in Pug:
```pug
=ScriptVariables::render()
```
For example inside a `<p></p>`:
```pug
p=ScriptVariables::render()
```

**Comment by GeometryRamiroGarcia** [comment]
I had already tried it like that but I printed it as text

**Comment by kylekatarnls** [comment]
If you need to dump HTML, you need the raw flag `!`:
```pug
!=ScriptVariables::render()
```
See the code section in the doc https://en.phug-lang.com#buffered-code

It's the same than in pugjs: https://pugjs.org/language/code.html
