### ISSUE TITLE
Sublime text

### ISSUE THREAD

**Issue by GeometryRamiroGarcia** [BKWLD/laravel-pug#55]
They know some plugin for the syntax highlighting of Pug in sublime text @weotch @justin-jewett 

Graciass

**Comment by weotch** [comment]
Sorry, not sure about Sublime.  We (at Bukwild) are either using Atom or VS Code.

**Comment by kylekatarnls** [comment]
The SublimeText plugin is still named `Jade` (the old name of Pug), but the highlight will still be right in most cases so you can install this one.
