### ISSUE TITLE
Nested renders cause mangled view cache

### ISSUE THREAD

**Issue by wolfgang42** [BKWLD/laravel-pug#56]
I have a template `search.pug` which uses Laravel's database pagination. I therefore have two views, `search.pug` and `vendor/pagination/default.pug`, and the search view calls `$results->links()` which renders the pagination. When I clear the view cache and load this page, it apparently caches the search view code into the cache file for the pagination view, causing errors when it later tries to render the search recursively into the spot where the pagination belongs.

This is confusing to explain, so I will try with a diagram. It is supposed to look like this:

**controller** renders **`search` view** which calls **`$results->links()`** which renders **pagination view**

but instead the code for the search view is cached as the pagination view, causing this:

**controller** renders **`search` view** which calls **`$results->links()`** which renders **(cached) `search` view** which causes an error.

I guess that this is because the Pug renderer is a shared singleton and something is getting confused, but I'm not entirely clear on how the cache file is selected. Possibly this is a problem with the Pug renderer itself, in which case let me know and I will file it there instead.

**Comment by kylekatarnls** [comment]
I added a vendor/pagination/default.pug and it properly displays.

I also can see that the rendered template of the pagination is properly renderer alone in a file and that in the page the links call is kept.

Can you provide a zip to reproduce?

**Comment by wolfgang42** [comment]
Ah, it seems that it only happens when the `search` view extends another template. Here is a full reproduction test case: [pug-repro.zip](https://github.com/BKWLD/laravel-pug/files/2295375/pug-repro.zip) (11.6 MiB)

**Comment by kylekatarnls** [comment]
thanks downloaded and reproduced, indeed, there is something that blocks in the paginator template. Curious because I have nearly the same in my project (except it uses JS-style) I test the different pieces of the paginator template.

**Comment by wolfgang42** [comment]
~~This problem seems to have gone away after an upgrade; I just tried the reproduction I linked above and once I run `composer upgrade` it doesn't have the problem any more.~~ *[Edit: never mind, I was confused.]* Relevant versions are:
  - Updating phug/util (0.4.15 => 0.4.16): Downloading (100%)         
  - Updating phug/reader (0.2.1 => 0.2.2): Downloading (100%)         
  - Updating phug/lexer (0.5.27 => 0.5.30): Downloading (100%)         
  - Updating phug/formatter (0.5.42 => 0.5.44): Downloading (100%)

**Comment by wolfgang42** [comment]
Sorry, no, I got confused and used the wrong copy of my test code. This still isn't working even with the latest versions of everything. Ignore my last comment.

**Comment by kylekatarnls** [comment]
Hi @wolfgang42, I finally understand what's happening. I think I can provide a fix soon.

**Comment by kylekatarnls** [comment]
Quick fixed on `dev-master`, can you try to update and see if all is fine for you? I have some tests to fix before releasing the tag will inspect deeper the root cause.

**Comment by kylekatarnls** [comment]
Clean solution here: https://github.com/BKWLD/laravel-pug/pull/57

So you could rather try the version `dev-isolated-compilation`
