### ISSUE TITLE
Ternary Operator issue

### ISSUE THREAD

**Issue by Riant** [BKWLD/laravel-pug#6]
The Pug code like below:
```
mixin avatar_img(default_src)
  - var _default_src = default_src || 'default-xxx.png'
  img(src=$userinfo['user_thumb'] ? $userinfo['user_thumb'] : _default_src)
```

When I call the mixin with `+avatar_img('abc')` or `+avatar_img()`, I got the error like below:
```
Use of undefined constant _default_src - assumed '_default_src' (View: xxx\xxxx\index.pug)
```

It looks like did not support the ternary operator like `a ? b : (c ? d : 'xxx')` or `a ? b : ( c || 'xxx')`.

Thanks.

**Comment by weotch** [comment]
I suggest you report this to https://github.com/pug-php/pug which is the package responsible for actually parsing the pug/jade
