### ISSUE TITLE
Pug code not rendered when including/extending .pug.blade.php and .pug.blade files

### ISSUE THREAD

**Issue by mhdalalwan** [BKWLD/laravel-pug#60]
All files with .pug extension are rendered, but using .pug.blade they do not get rendered.

**Comment by kylekatarnls** [comment]
Hi, I just tested with laravel-pug 1.7.1 in Laravel 5.8, I created 2 templates: `page1.pug.blade` then called `return view('page1');` and created `page2.pug.blade.php` and called `return view('page2');`

Both displayed properly.

Can you provide more details? Your code, templates paths and names, library and framework versions, and the exception you get.

**Comment by mhdalalwan** [comment]
I have 2 files, one called layout.pug.blade.php and the other called home.pug.blade.php
When i tried to extends the layout in home this is what i get.

`html head meta(name='viewport', content='width=device-width,initial-scale=1,shrink-to-fit=no') title #{title} link(rel="stylesheet", href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css") link(rel="stylesheet", href="https://use.fontawesome.com/releases/v5.8.1/css/all.css") link(rel="stylesheet" href="./css/app.css" ) body //- including header | include layouts/headerDefault | block content include layouts/footer script(src="http://code.jquery.com/jquery-latest.min.js") script(src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js") script(src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js") block scripts script(src="./js/app.js")`

So it seems that pug code is not rendered first.

**Comment by kylekatarnls** [comment]
Problem found, the Pug-php engine will just consider the "real" extension (`pathinfo($path, PATHINFO_EXTENSION)`) for include/extend, so .pug.blade.php are PHP files for Pug, and .pug.blade are Blade, none are handled and so Pug returns the input as is.

This will need [phug/compiler](https://github.com/phug-php/compiler) to support macro-extensions.

**Comment by kylekatarnls** [comment]
Will be fixed in the next release via #61.

**Comment by kylekatarnls** [comment]
1.7.2 released. use `composer update` to get last `phug/compiler` and last `bkwld/laravel-pug`

**Comment by mhdalalwan** [comment]
Still not working

I have 2 pages

- layout.pug.blade.php
`h2 test from layout
block content
`
- welcome.pug.blade.php
`extends layout.pug.blade.php
block content
h2 test from welcome`


Result

> `h2 test from layout block content
> test from welcome`

**Comment by kylekatarnls** [comment]
It should be just `extends layout` instead of `extends layout.pug.blade.php`.

But usage with full name seems fair. I will also add an option for that.

**Comment by kylekatarnls** [comment]
<s>You can update again, the `phug/compiler` **0.5.23** allow now both `extends layout` and `extends layout.pug.blade.php`</s>

**Comment by kylekatarnls** [comment]
**0.5.23** is still broken, I will update it.

**Comment by kylekatarnls** [comment]
You can update again, the `phug/compiler` **0.5.24** allow now both `extends layout` and `extends layout.pug.blade.php`

**Comment by mhdalalwan** [comment]
0.5.24 is not working for extends

<img width="308" alt="Screen Shot 2019-04-29 at 4 59 55 PM" src="https://user-images.githubusercontent.com/5927525/56901190-3d768580-6aa0-11e9-9b23-2ed2be092e33.png">

**Comment by kylekatarnls** [comment]
It's working on Travis with the following test:
https://github.com/BKWLD/laravel-pug/blob/master/tests/ServiceProviderTest.php#L482
And files here:
https://github.com/BKWLD/laravel-pug/tree/master/tests/composite-extension

It uses the informations you gave me, please check what's different from your case.
