### ISSUE TITLE
PhpStorm

### ISSUE THREAD

**Issue by IAntonioDev** [BKWLD/laravel-pug#62]
Hello, how can I get help with all the Laravel methods and global variables inside a .pug or .pug.blade file? if I use
`:php dd(app())`
It works and shows the app() data, but how can I get help as when I'm Working with Blade?

**Comment by IAntonioDev** [comment]
Also how do you get help on VS Code?

**Comment by kylekatarnls** [comment]
IDEs need language definition files. They can be provided by plugins. As far as I know, such plugins exist for Pug.js, but not for Pug-php.

https://blog.jetbrains.com/idea/2013/01/how-to-write-custom-language-support-plugins/
https://macromates.com/manual/en/language_grammars

Any help in creating such plugins is welcome.
