### ISSUE TITLE
New Packagist hook

### ISSUE THREAD

**Issue by kylekatarnls** [BKWLD/laravel-pug#63]
Hi @weotch, the new packagist hook does not seem to be installed as auto-update did not take the last commit: https://packagist.org/packages/bkwld/laravel-pug#dev-master (commit should be 61beabb35e455accb5af1e6f80f01376b0fa8969). Could you please configure Packagist the new way:
https://packagist.org/about#how-to-update-packages

Thanks.

**Comment by weotch** [comment]
I _think_ this is fixed now.  Also, I've promoted you to Admin of this package as well.

**Comment by kylekatarnls** [comment]
It's up to date, perfect! Thanks.
