### ISSUE TITLE
Question about pugjs => true

### ISSUE THREAD

**Issue by sofubi** [BKWLD/laravel-pug#64]
Hey there, I'm having issues getting `'pugjs' => true ` to work in the `/config/laravel-pug.php` file. I've set the option but it doesn't seem to be working. I've surfed issues and saw someone else had this issue but they were on a vagrant setup. I'm currently working on XUbuntu 18.04. I'm able to reach the site just fine but I'm getting errors that would indicate that PHP is still rendering out of the .pug files. Any help with this would be appreciated.

**Comment by sofubi** [comment]
Just wanted to add that #53 is very similar to my issue and is what I was referring to.

**Comment by kylekatarnls** [comment]
Please provide the exact errors you get, and the view you're rendering.

**Comment by kylekatarnls** [comment]
I consider this as solved, if you still have trouble, please provide us a way to reproduce your bug and your exact error and I would re-open this.
