### ISSUE TITLE
how to use relationship output in page.pug 

### ISSUE THREAD

**Issue by smsonn** [BKWLD/laravel-pug#65]
how to use relationship output in page.pug 
@foreach($request as $g)
{!! $g->user_id()->first()->name !!}
@endforeach

**Comment by kylekatarnls** [comment]
```pug
each g in request
  !=g.user_id().first().name
```

Think Pug first and your code will be shorter.

**Comment by smsonn** [comment]
Unfortunately it does not work
Function name must be a string (View:
C:\Users\smsonn\Desktop\vargets\resources\views\index.pug)

**Comment by smsonn** [comment]
Unfortunately it does not work.
Error
Function name must be a string

**Comment by smsonn** [comment]
Unfortunately it does not work.
Error
Function name must be a string

**Comment by kylekatarnls** [comment]
It's very strange that `user_id` would be a method. I think it's not a problem from the template but from the data.

Try to debug it step by step, so with the error line, you will now what is missing:

```pug
unless is_array(request)
  p request should be an array
each g in request
  p g
  - var_dump(g)
  p g.user_id()
  - var_dump(g.user_id())
  p g.user_id().first()
  - var_dump(g.user_id().first())
  p g.user_id().first().name
  - var_dump(g.user_id().first().name)
```
