### ISSUE TITLE
How to pass variables using View::composer()?

### ISSUE THREAD

**Issue by picbenoit** [BKWLD/laravel-pug#66]
Hello,

I try to use View::composer to share variables to specific view, but it not working.

`View::share('myvar', 'myval'); // is working as well but share the variable to all view.`

```
View::composer('partials._footer', function ($view) {
            $view->with('myvar', 'myval');
}); // This code is not working
```

My pug view is called in another pug file like :
```
footer
    include /partials/_footer
```
I also tried that code as suggest in #23 but it's not working too :
`footer!= view('partials._footer')`

Thank you for your help,

Ben.

**Comment by kylekatarnls** [comment]
I think there is no equivalent for this feature in Pug. As we mimic the JS variable scoping. I'm not sure it would be possible.

But if you use `.pug.blade` files, you still can call Blade statements:
```pug
footer
    | @include('partials._footer')
```

I think the `$view->with('myvar', 'myval');` is executed, but as the engine and variables are already set, it does not propagate to the view.

**Comment by picbenoit** [comment]
I tried to change my file to pug.blade and pug.blade.php but still doesnot work (I had already tried this solution before it seems to me).
Seems laravel pug not supported view composer yet.
I will continue to use global share for my common elements for the moment. Thank you @kylekatarnls for your help.

Ben

**Comment by kylekatarnls** [comment]
In fact you just miss the return :)
```php
View::composer('partials._footer', function ($view) {
    return $view->with('myvar', 'myval');
});
```

```pug
footer!= view('partials._footer')
```

**Comment by picbenoit** [comment]
Great ! Thank you so muck @kylekatarnls 
Just missing the return as you told on your post. 
The example on Laravel documentation is not complete (no mention of return) :
```
        // Using Closure based composers...
        View::composer('dashboard', function ($view) {
            //
        });
```
To be complete, I can keep my file as pug, don't need to change to pug.blade or pug.blade.php

**Comment by kylekatarnls** [comment]
Yes, `.pug` is preferable as long as you don't need specific Blade features (and most of them have equivalent ones in Pug). I mentioned it to test `| @include()`
