### ISSUE TITLE
Same variable name as in loop, causes unexpected behavior

### ISSUE THREAD

**Issue by OccTherapist** [BKWLD/laravel-pug#67]
I ran into this issue today where I passed `['bar' => $bar, 'foo' => $foo]` to the view. Then when iterationg over `$foo->bar as $bar`, the `$bar` passed from the controller got replaced. Even after the loop.
 
```pug
ul
  for $bar in $foo->bars
    li #{ $bar }

section.info
  h1 #{ $bar->name }
```

`$bar` is now equal to `$foo->bar`.

**Comment by kylekatarnls** [comment]
Hi @OccTherapist, it's how PHP works: https://3v4l.org/M7XmJ

We use the PHP `foreach` statement to handle those loops.

But indeed pugjs scope the iteration variable into the loop and we should try to mimic this behavior, so I opened an issue to update the renderer:
https://github.com/phug-php/phug/issues/41

**Comment by kylekatarnls** [comment]
Fixed, you can run `composer update` to get the compiler fix.
