### ISSUE TITLE
Errors with evaluating expressions

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [BKWLD/laravel-pug#69]
Im using this pug expression to spit out some inline js in a `.pug` template
```
script
    = "SUBSCRIBED = " . (isset(stripe) && stripe.product ? "true" : "false") . ";"
```
I want this to spit out something like this:
```
<script>
    SUBSCRIBED = true;
</script>
```
The current error Im getting is 
```
syntax error, unexpected ';', expecting ',' or ')' 
```
I have tried all manner of variations on this and im constantly getting errors which I dont understand. I tried using `+` for the string concatenation, I tried using backticks, none of it is working. I dont understand if im in php mode or js mode, I havent set the mode in the config so I assume its js mode, but its so hard to tell what the hell is going on or how to fix it

**Comment by kylekatarnls** [comment]
Hi,

Concatenation in JS mode is `+` , not `.` and js-phpize (the JS to PHP compiler) do the `isset()` for you, so it's simply:
```pug
script
    = "SUBSCRIBED = " + (stripe.product ? "true" : "false") + ";"
```

And I would even recommend:
```pug
script
    = "SUBSCRIBED = " + JSON.stringify(!!stripe.product) + ";"
```

This way you don't have to hard-code "true" and "false" with mistype risk.
