### ISSUE TITLE
[Lumen 6.0] Unsupported Laravel Version

### ISSUE THREAD

**Issue by Smankusors** [BKWLD/laravel-pug#72]
Actually, there's something breaking when checking the version. When you call [`$app->version()`](https://github.com/BKWLD/laravel-pug/blob/master/src/ServiceProvider.php#L122), Lumen 6.0 will actually returns `"Lumen (6.0.2) (Laravel Components ^6.0)"` (note that there's caret after "Laravel Components").

Interestingly, when this called on Laravel 6.0, that function would return `"6.0.3"` instead. Also in Lumen 6.0, it didn't have `VERSION` constant. I feels like there's some inconsistency with Laravel code here. 

What do you think? Should this be issue on your package or this should be Laravel's problem?

Thanks,

**Comment by kylekatarnls** [comment]
If Lumen version is no longer synchronized with Laravel components version, we'll have to check if there is a proper way to get the exact version of Laravel components, else we could: ask Lumen team to create it and meanwhile guess it from ^6.0 in the string.

**Comment by kylekatarnls** [comment]
At a first sight, the version string in Lumen is hard-coded so probably has not the laravel components version alone anywhere: https://github.com/laravel/lumen-framework/blob/9b3182e48142e3e61648ed3733d18c0bfbee2f0d/src/Application.php#L143

**Comment by kylekatarnls** [comment]
For 4 to 6 version support, simply ignoring `^` and other possible symbols will be fine, I jut hope nothing incompatible would come up before version 7.

**Comment by kylekatarnls** [comment]
Please try to update to [1.9.1](https://github.com/BKWLD/laravel-pug/releases/tag/1.9.1)

**Comment by Smankusors** [comment]
yeap that fixed this. Thanks 😄
