### ISSUE TITLE
Another issue with the Exception Class

### ISSUE THREAD

**Issue by OccTherapist** [BKWLD/laravel-pug#73]
Hi, on another project of mine I get this Exception

```
Class 'Facade\Ignition\Exceptions\ViewException' not found 
```

The project runs on Laravel  version 5.8.

**Comment by kylekatarnls** [comment]
Hi thanks for your report. I will wait for Travis build before tagging a new release, but you can yet test the fix on `"bkwld/laravel-pug": "dev-master"`
