### ISSUE TITLE
Doesn't expand blade variable in pug's html element attributes

### ISSUE THREAD

**Issue by kohki-shikata** [BKWLD/laravel-pug#74]
This is OK
`a(href="path/to/somewhere") {{ $path->somewhere }} - Path to Somewhwere`

And, this has not expanded.
`a(href="{{ $path->somewhere }}") Path to somewhere`

Finally, this has worked.
```
.
  <a href="{{ $path->somewhere }}"> Path to somewhere</a>
```
Ah, it's non-sense at laravel-pug, I think.

I need to set attribute as dynamically. How should I do?

**Comment by kylekatarnls** [comment]
The expectation you mention and problem here is not clear to me, but maybe you want to simply do:
```pug
a(href=path.somewhere) Path to somewhere
```
For the attribute, or for content:
```pug
a(href="path/to/somewhere")
  =path.somewhere
  | Path to somewhere
```
See the syntax here: https://phug-lang.com

And prefer pug syntax over blade syntax (it's less verbose).

**Comment by kohki-shikata** [comment]
Thanks, Work it.
