### ISSUE TITLE
Provide support for different file extension order

### ISSUE THREAD

**Issue by lastwhitebird** [BKWLD/laravel-pug#75]
Currently there's no syntax highlighting support for "pug.blade" or "jade.blade" files. 
I'm suggesting using the reverse order (along with the orginal) in /src/ServiceProvider.php:

```php    
if ($subExtension) {
        $subExtension2 = substr($subExtension, 1) . '.';
            $this->app['view']->addExtension($subExtension2.'pug'  , 'pug' . $subExtension);
            $this->app['view']->addExtension($subExtension2.'pug.php', 'pug' . $subExtension);
            $this->app['view']->addExtension($subExtension2.'jade' , 'pug' . $subExtension);
            $this->app['view']->addExtension($subExtension2.'jade.php', 'pug' . $subExtension);
    }
```
i.e. blade.pug/blade.jade

Screenshot with result:
![Screenshot_20191224_152357](https://user-images.githubusercontent.com/13571877/71411178-c8c10e80-2661-11ea-9b2d-69df0dba30ac.png)

**Comment by kylekatarnls** [comment]
This would break existing applications when users will update, but we can consider allowing both orders.

Meanwhile, you should check if you can use only `.pug` with no blade in your template. Be aware there is equivalent syntax in Pug for every feature of Blade. So to avoid having in your templates different syntaxes mixed for similar purpose you should try using pure Pug templates.

**Comment by kylekatarnls** [comment]
With the version 1.11.0, you can now swap order of pug and blade/jade in the files extension.
