### ISSUE TITLE
Laravel pug for Laravel 7

### ISSUE THREAD

**Issue by anurat** [BKWLD/laravel-pug#81]
Hi, Thank you for porting pug to laravel.

I know Laravel 7 is pretty new but it would be great to be able to use pug in Laravel 7.
Any plan to support it soon?

**Comment by kylekatarnls** [comment]
Hello, a version bump in composer.json should be enough as there is no particular breaking change in views. You can already test it by requiring `"bkwld/laravel-pug": "dev-master"` I will also test with a fresh project and tag a version if it's OK.

**Comment by anurat** [comment]
Thank you, 

I did not know that I can require "bkwld/laravel-pug" : "dev-master".  
I will do that.

Best,

**Comment by kylekatarnls** [comment]
Released as [version 2.0.0](https://github.com/BKWLD/laravel-pug/releases/tag/2.0.0)
