### ISSUE TITLE
Checking null value in pug from db call

### ISSUE THREAD

**Issue by JonDeschenes** [BKWLD/laravel-pug#82]
I'm having an issue checking a null value that is inside an object i got from my database. When i'm trying to check that value i get an array (json) of the object. Then, it's impossible to check if a value is null. With blade syntax it works fine.

When creating a custom variable and assigning it null everything works. 

Exemple:
var_dump of what i get from database : 
![image](https://user-images.githubusercontent.com/39345951/78055649-d6b5b800-7351-11ea-939d-a896916ab5c5.png)

Trying to access "apart_number" : 
![image](https://user-images.githubusercontent.com/39345951/78055922-47f56b00-7352-11ea-890c-2d5d6a249b32.png)

Error : 
![image](https://user-images.githubusercontent.com/39345951/78055998-652a3980-7352-11ea-842a-22e0b67faba4.png)

When checking at index [0] cause it tell me it's in an array : 
![image](https://user-images.githubusercontent.com/39345951/78056210-bcc8a500-7352-11ea-82b0-458476f7ebb0.png)

other field work fine!

Sorry for my poor English,
Hope you can help me thx

**Comment by kylekatarnls** [comment]
I confirm this bug. It may be due to the magic methods of `Model` class.

Meanwhile you can use:
```pug
h1=test.getAttribute('apart_number')
```

**Comment by kylekatarnls** [comment]
Hi, here are some more precise explanations. If you would have a public method `foobar` in some object `test` (of any class, Model or not), Pug would allow you to pass this method in JS-style:
```pug
mixin title(func)
  h1=func()

+title(test.foobar)
//- equivalent to:
h1=test.foobar()
```
As you may note, at the mixin call moment, we're not able to see that `test.foobar`will be called as a method/function. So we will check public properties definition of the class, if foobar is declared as a property/member, so we assume it's not a method and send `$test->foobar` ( `null` if not set).

But if we don't find it as a property definition of the class, we look for a method definition, if there no definition either, then we look for magic methods (`__get` for property or `__call` for method). In the case of Laravel models, both `__get` and `__call` exit so we still don't know what it could be and so we pass it as `array($test, 'foobar')` under the hood which can allow to retrieve either the property or to call the method on need.

We also check `__isset` magic method to check if a property exist but Eloquent model return `false` in this case for `null` values so it doesn't help.

So I don't have yet a solution that will not break an other feature.

**Comment by JonDeschenes** [comment]
Hi, thanks for the quick replies. I'll use the alternative method you proposed with the .getAttribute().
Thx :)

I know its not related to this bug but I would like to know if there was a way to get the old() value of an input just like in blade when we use old('test') ?

**Comment by kylekatarnls** [comment]
I just though about an other alternative you may prefer: you can add getters in your model:

```php
class Address ...
    public function geApartNumber()
    {
        return $this->apart_number;
    }
```

Then in the template you can call:
```pug
h1=test.apartNumber
```
Case does not matter (ApartNumber, apartnumber, etc.) as you can also reuse the exact same name naming the method `geApart_number`

Getters are often considered as a general best practice. As I always add getters and setters to not access directly the DB properties, it explains why I never fell on such issue myself.

**Comment by kylekatarnls** [comment]
Hi, I'm preparing a fix for the cast to string. The handler of the dot operator (when the left value type cannot be determined) will now be an enhanced object rather than an array, This object will be callable like the array currently is (to support the `+title(test.foobar)` case) and will be able to be casted to string using the `__toString` method, so assuming it's not a method in this case).

It raised an other interesting case:
```pug
if test.apartNumber
  p There is a number
else
  p There is no number
```

In this particular we actually could know `test.apartNumber` is not expected to be a callable as `if` will check it as a boolean value. So I also decide to provide a `__toBoolean` communication system between js-phpize and phug, so phug can inform a value will be tested as a condition, and formatters like js-phpize can provide a way to cast to boolean for such case.

**Comment by kylekatarnls** [comment]
You can now update your dependencies with `composer update` and be able to use:

```pug
p!=test.apartNumber
p=test.apartNumber

unless test.apartNumber
    p No number

if test.apartNumber
    p Number filled
```
