### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Coornifex** [BKWLD/laravel-pug#88]
Hi,

Can you tell me if this package will support PHP 8 anytime soon ?

Regards.

**Comment by kylekatarnls** [comment]
There is likely no blocker as pug-php itself runs on PHP 8, so if every tests pass, we'll just have to allow it in composer and release:
https://travis-ci.org/github/BKWLD/laravel-pug/jobs/747182578

**Comment by kylekatarnls** [comment]
[Fixed in 2.3.0](https://github.com/BKWLD/laravel-pug/releases/tag/2.3.0)
