### ISSUE TITLE
Issue implementing Laraform

### ISSUE THREAD

**Issue by sebszocinski** [BKWLD/laravel-pug#95]
[Laraform](https://laraform.io/) has a render function to load forms that looks like this:
```
	/**
	 * Renders form DOM element
	 *
	 * @return string
	 */
	public function render() {
    $model = $this->storePath ? "store-path=\"{$this->storePath}\"" : '';
    $form = ":form=\"{$this->toProp()}\"";

		return "<{$this->getComponent()} $form $model></{$this->getComponent()}>";
	}
```

Frontend code: 
```
<div id"#form"> {!! $form->render() !!} </div>
```

When I try to render this using pug I get the following error from Vue:
```
Invalid prop: type check failed for prop "form". Expected Object, got String with value "[object Object]".
```

Looks like it's an issue with unescaping the $form function? I've tried `!{$form->render()}` but that doesn't seem to work.

Any pointers?

**Comment by kylekatarnls** [comment]
With expressionLanguage => js (default)
```pug
#form!=form.render()
```

With expressionLanguage => php
```pug
#form!=$form->render()
```
