### ISSUE TITLE
colon attribute with JS object is being duplicated

### ISSUE THREAD

**Issue by sebszocinski** [BKWLD/laravel-pug#96]
I'm trying to pass JS object to an attribute for a Vue component and if I do this:
```pug
div(:foo='{"key":"value"}')
```
It renders this:
```html
<div :foo="{"key":"value"}" foo="[object Object]"></div>
```
And my Vue component fails because it's trying to read the `foo` attribute instead.

Why is this happening? and how can we prevent it?

**Comment by kylekatarnls** [comment]
Hello, that's a good question. When I try it in https://phug-lang.com/#try it properly renders as:
```html
<div :foo="{&quot;key&quot;:&quot;value&quot;}"></div>
```

So it does not comes from the Pug engine, there is something specific Laravel, laravel-pug adapter or your specific stack. I will try to reproduce the bug in tests.

**Comment by kylekatarnls** [comment]
Sorry, I tried to reproduce, but I always get the content above with only 1 attribute using last version or Laravel and laravel-pug.

Please provide a minimum standalone steps to reproduce the bug. There is very likely something more in your stack which rewrite the view.

It might be a conflict or simply a bug from this other library. For instance try:

```pug
| <div :foo='{"key":"value"}'>Content</div>
```

When doing this, Pug just does nothing and pass the HTML as is. If it's still modified, then it means you would have the exact same issue without Pug (with pure HTML views).
