### ISSUE TITLE
iif is not working

### ISSUE THREAD

**Issue by jcastroa87** [BKWLD/laravel-pug#97]
I have a little problem with evaluation of string variables

`header()&attributes(pageTitle === 'NFT Marketplace' ? {'class': 'navbar d-block navbar-sticky navbar-expand-lg navbar-light position-absolute w-100'} : {'class': 'navbar d-block navbar-sticky navbar-expand-lg navbar-light bg-light'})
`
If have this evaluation as iif "pageTitle === 'NFT Marketplace'" work correctly when i use https://prepros.io/ but on laravel-pug always return true even if variable is not true.

Do i miss some configuration?

Thanks

P.D.: version laravel-pug is 2.3

**Comment by kylekatarnls** [comment]
Hello, it's a precedence issue from our side, but you just need to enforce it with parentheses to work-around:
`(pageTitle === 'NFT Marketplace')`

**Comment by jcastroa87** [comment]
Everything works perfect now, thank you very much

**Comment by kylekatarnls** [comment]
It should be fixed with `phug-php/phug` **1.11.0**, now parentheses should no longer be needed.

**Comment by jcastroa87** [comment]
this will be updated in this package or i need to manually update?

**Comment by kylekatarnls** [comment]
You can simply run:
`composer u bkwld/laravel-pug -w`

to update the package and its dependencies. Or a global `composer u` to update everything.

**Comment by jcastroa87** [comment]
ty
